# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

    - task: AzureRmWebAppDeployment@4
      inputs:
       ConnectionType: 'AzureRM'
       azureSubscription: 'Free Trial(1)(ce6bcc62-114e-41dd-9733-2fb49649b24a)'
       appType: 'webApp'
       WebAppName: 'Test75786'
       VirtualApplication: 'Test75786'
       packageForLinux: '$(System.DefaultWorkingDirectory)*.zip'